@id=3c5c7132-77c2-4afc-8486-7a2ca3a11ea4
    
PUT http://localhost:5164/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine 2",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "lastModifiedDateTime": "2022-04-06T12:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}